# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'schedule' do
pod 'BTNavigationDropdownMenu'
end

target 'scheduleTests' do
pod 'BTNavigationDropdownMenu'

end

target 'scheduleUITests' do
pod 'BTNavigationDropdownMenu'

end

target 'watch_schedule' do

end

target 'watch_schedule Extension' do

end

